#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Luakit desktop='^2'
bspc rule -a Brave desktop='^2'
bspc rule -a Steam desktop='^3'
bspc rule -a "" desktop='^4' focus=off follow=off
bspc rule -a discord desktop='^5' focus=off follow=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/lemonbar/lemonbar.sh
